### ISSUE TITLE
6x6 its missing ESC and Function buttons

### ISSUE THREAD

**Issue by Nurtekin429** [mjohns/dactyl-cc#10]
I'm used to use Kinesis advantage this had the same thumb buttons.
I think its better for me then manufold.
Its great design what you have done. 
I have printed left and right. 
Is is possible to make 6x6. Its now missing ESC and Function buttons.
They are very useful.
Thanks in advance.

**Comment by mjohns** [comment]
The esc/function keys on the kinesis are pretty different in location and sizing. It would be possible to add another row on top but it would be an involved process as this isn't a parametric layout like with the dactyl manuform. You would need to update key_data.h/cc with the new row of keys and then update the wall generating code to use those new keys instead of the existing top row.

**Comment by AzizZayed** [comment]
I would also like to add a row on top. Could you show me how? Or is there a resource from which I can understand your code so that I can make the necessary changes?
