### ISSUE TITLE
Case material

### ISSUE THREAD

**Issue by ntarocco** [mjohns/dactyl-cc#3]
Hi, thanks a lot for this repo! I am about to build my keyboard as yours! I love it.

I am still not convinced which material to use to 3d print the case. I am worried about the finishing look&feel.
Which one did you use? Are you happy with robustness and look&feel?

Maybe, it would be great to add some details about your build:
* Material: ABS, PLA or PEGT?
* Infill: 20%?
*. nice to have: any recommendation on which 3d print website to use, if you have any experience?

Thanks!

**Comment by 20lives** [comment]
I didn't print this variation but I have printed countless others.
Mainly the material will affect only the sturdiness of it, so any material could come out great.
Infill is also partially irrelevant since the walls are really thin.
What makes the biggest difference is the: material quality, printer quality, printer calibration, printing speed.
Moreover, there is a lot of post-processing that can be done to improve "look&feel": sanding, finishing, coating.

The best suggestion I can make is if you have the time: buy your own 3d printer and do it yourself.

**Comment by mjohns** [comment]
I have printed all of my keyboards using PLA and the default Cura Ender3 profile (infill 20%). Using tree supports does save a fair bit of time and has worked well for me. I primed and spray painted (https://imgur.com/a/LsxRFcR) the keyboard which really improves the finish and I have had no problems with they keyboards over the past few years.

I printed them myself so I can't recommend any site for that.

**Comment by ntarocco** [comment]
Thanks a lot for your answers! I really don't want to buy a 3d printer right now and I don't have access to any.
I have ordered online the case printed with PLA, infill 20%, black.
I was also planning to do some finishing and painting, I will post pictures when ready!
