### ISSUE TITLE
Regarding similarity to Kinesis

### ISSUE THREAD

**Issue by mseflek** [mjohns/dactyl-cc#5]
Hi, Thanks for putting this together. As a long time Kinesis user I think this will solve a lot of problems I am having. Couple of quick questions:

1. Have you designed/use wrist rests with this?
2. Is the thumb cluster at the same height as it is on the Kinesis, or is it slight lower?
3. If you've used both, do you have a clear preference for this vs. the Kinesis?
4. Lastly: I noticed you reused the 1.25u keys on the pinky. Is it easy to make these 1U instead?

**Comment by hasufell** [comment]
I'm also concerned about the thumb cluster, since that's one of the maon reasons to look for alternatives (they're too high).

**Comment by mjohns** [comment]
1. I used a wrist pad (https://www.amazon.com/Glorious-Gaming-Wrist-Pad-Rest/dp/B0191YRMCO) on top of a 1 inch tall piece of wood. Nothing 3d printed / integrated.
2. The thumb cluster is at the same height relative to the keywell as the kinesis. The whole keyboard is slightly lower than the kinesis.
3. I prefer this over the kinesis because of QMK and the ability to adjust the position of the two keywells independently.
4. You would have to go into key_data.cc and adjust the x offset of key_caps. https://github.com/mjohns/dactyl-cc/blob/master/src/key_data.cc#L183. Changing -22.597 to something around -20.
